### ISSUE TITLE
When I try to install it via pip it doesn't work

### ISSUE THREAD

**Issue by AnANTKA** [media2x/realcugan-ncnn-vulkan-python#1]
When I try to install it I get this error : 

C:\Users\pexal>pip install realcugan-ncnn-vulkan-python
Collecting realcugan-ncnn-vulkan-python
  Using cached realcugan-ncnn-vulkan-python-1.0.2.tar.gz (49.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pillow in c:\users\pexal\appdata\local\programs\python\python310\lib\site-packages (from realcugan-ncnn-vulkan-python) (9.1.0)
Building wheels for collected packages: realcugan-ncnn-vulkan-python
  Building wheel for realcugan-ncnn-vulkan-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for realcugan-ncnn-vulkan-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [84 lines of output]
      running bdist_wheel
      running build
      running build_ext
      -- The C compiler identification is unknown
      -- The CXX compiler identification is unknown
      CMake Error at CMakeLists.txt:5 (project):
        No CMAKE_C_COMPILER could be found.

        Tell CMake where to find the compiler by setting either the environment
        variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
        the compiler, or to the compiler name if it is in the PATH.

      CMake Error at CMakeLists.txt:5 (project):
        No CMAKE_CXX_COMPILER could be found.

        Tell CMake where to find the compiler by setting either the environment
        variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
        to the compiler, or to the compiler name if it is in the PATH.

      -- Configuring incomplete, errors occurred!
      See also "C:/Users/pexal/AppData/Local/Temp/pip-install-x_6p5of1/realcugan-ncnn-vulkan-python_556207dadccf4565a63b4aa203dcceb7/build/temp.win-amd64-3.10/Release_realcugan-ncnn-vulkan-python/CMakeFiles/CMakeOutput.log".
      See also "C:/Users/pexal/AppData/Local/Temp/pip-install-x_6p5of1/realcugan-ncnn-vulkan-python_556207dadccf4565a63b4aa203dcceb7/build/temp.win-amd64-3.10/Release_realcugan-ncnn-vulkan-python/CMakeFiles/CMakeError.log".

      ==> Configuring:
      $ cmake -S C:\Users\pexal\AppData\Local\Temp\pip-install-x_6p5of1\realcugan-ncnn-vulkan-python_556207dadccf4565a63b4aa203dcceb7\realcugan_ncnn_vulkan_python -B C:\Users\pexal\AppData\Local\Temp\pip-install-x_6p5of1\realcugan-ncnn-vulkan-python_556207dadccf4565a63b4aa203dcceb7\build\temp.win-amd64-3.10\Release_realcugan-ncnn-vulkan-python -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=C:\Users\pexal\AppData\Local\Temp\pip-install-x_6p5of1\realcugan-ncnn-vulkan-python_556207dadccf4565a63b4aa203dcceb7\build\lib.win-amd64-3.10\realcugan_ncnn_vulkan_python -DBUILD_SHARED_LIBS:BOOL=OFF -DCALL_FROM_SETUP_PY:BOOL=ON

      ==> Building:
      $ cmake --build C:\Users\pexal\AppData\Local\Temp\pip-install-x_6p5of1\realcugan-ncnn-vulkan-python_556207dadccf4565a63b4aa203dcceb7\build\temp.win-amd64-3.10\Release_realcugan-ncnn-vulkan-python --config Release

      ==> Installing:
      $ cmake --install C:\Users\pexal\AppData\Local\Temp\pip-install-x_6p5of1\realcugan-ncnn-vulkan-python_556207dadccf4565a63b4aa203dcceb7\build\temp.win-amd64-3.10\Release_realcugan-ncnn-vulkan-python

      Traceback (most recent call last):
        File "C:\Users\pexal\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\pexal\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\pexal\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\pexal\AppData\Local\Temp\pip-build-env-s0g1z41p\overlay\Lib\site-packages\setuptools\build_meta.py", line 244, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "C:\Users\pexal\AppData\Local\Temp\pip-build-env-s0g1z41p\overlay\Lib\site-packages\setuptools\build_meta.py", line 229, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\pexal\AppData\Local\Temp\pip-build-env-s0g1z41p\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 15, in <module>
          setuptools.setup(
        File "C:\Users\pexal\AppData\Local\Temp\pip-build-env-s0g1z41p\overlay\Lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\pexal\AppData\Local\Temp\pip-build-env-s0g1z41p\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
        File "C:\Users\pexal\AppData\Local\Temp\pip-build-env-s0g1z41p\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
          dist.run_commands()
        File "C:\Users\pexal\AppData\Local\Temp\pip-build-env-s0g1z41p\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "C:\Users\pexal\AppData\Local\Temp\pip-build-env-s0g1z41p\overlay\Lib\site-packages\setuptools\dist.py", line 1214, in run_command
          super().run_command(command)
        File "C:\Users\pexal\AppData\Local\Temp\pip-build-env-s0g1z41p\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\pexal\AppData\Local\Temp\pip-build-env-s0g1z41p\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "C:\Users\pexal\AppData\Local\Temp\pip-build-env-s0g1z41p\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\pexal\AppData\Local\Temp\pip-build-env-s0g1z41p\overlay\Lib\site-packages\setuptools\dist.py", line 1214, in run_command
          super().run_command(command)
        File "C:\Users\pexal\AppData\Local\Temp\pip-build-env-s0g1z41p\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\pexal\AppData\Local\Temp\pip-build-env-s0g1z41p\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\pexal\AppData\Local\Temp\pip-build-env-s0g1z41p\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\pexal\AppData\Local\Temp\pip-build-env-s0g1z41p\overlay\Lib\site-packages\setuptools\dist.py", line 1214, in run_command
          super().run_command(command)
        File "C:\Users\pexal\AppData\Local\Temp\pip-build-env-s0g1z41p\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\pexal\AppData\Local\Temp\pip-build-env-s0g1z41p\overlay\Lib\site-packages\cmake_build_extension\build_extension.py", line 110, in run
          self.build_extension(ext)
        File "C:\Users\pexal\AppData\Local\Temp\pip-build-env-s0g1z41p\overlay\Lib\site-packages\cmake_build_extension\build_extension.py", line 224, in build_extension
          subprocess.check_call(configure_command)
        File "C:\Users\pexal\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '-S', 'C:\\Users\\pexal\\AppData\\Local\\Temp\\pip-install-x_6p5of1\\realcugan-ncnn-vulkan-python_556207dadccf4565a63b4aa203dcceb7\\realcugan_ncnn_vulkan_python', '-B', 'C:\\Users\\pexal\\AppData\\Local\\Temp\\pip-install-x_6p5of1\\realcugan-ncnn-vulkan-python_556207dadccf4565a63b4aa203dcceb7\\build\\temp.win-amd64-3.10\\Release_realcugan-ncnn-vulkan-python', '-GNinja', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX:PATH=C:\\Users\\pexal\\AppData\\Local\\Temp\\pip-install-x_6p5of1\\realcugan-ncnn-vulkan-python_556207dadccf4565a63b4aa203dcceb7\\build\\lib.win-amd64-3.10\\realcugan_ncnn_vulkan_python', '-DBUILD_SHARED_LIBS:BOOL=OFF', '-DCALL_FROM_SETUP_PY:BOOL=ON']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for realcugan-ncnn-vulkan-python
Failed to build realcugan-ncnn-vulkan-python
ERROR: Could not build wheels for realcugan-ncnn-vulkan-python, which is required to install pyproject.toml-based projects

My python version is 3.10.4 
It says that it can't find cmake and I don't know how to fix it

**Comment by ArchieMeng** [comment]
> [Build](https://github.com/media2x/realcugan-ncnn-vulkan-python#build)
> First, you have to install python, python development package (Python native development libs in Visual Studio), vulkan SDK and SWIG on your platform. And then, there are two ways to build it

Installing from pip requires the host to have appropriate C++ compiler (MSVC or GCC), CMake, SWIG and Vulkan development libs.
If you need to have it working out-of-box, please use the binary wheels on https://github.com/media2x/realcugan-ncnn-vulkan-python/releases .

**Comment by God-damnit-all** [comment]
> > [Build](https://github.com/media2x/realcugan-ncnn-vulkan-python#build)
> > First, you have to install python, python development package (Python native development libs in Visual Studio), vulkan SDK and SWIG on your platform. And then, there are two ways to build it
> 
> Installing from pip requires the host to have appropriate C++ compiler (MSVC or GCC), CMake, SWIG and Vulkan development libs. If you need to have it working out-of-box, please use the binary wheels on https://github.com/media2x/realcugan-ncnn-vulkan-python/releases .

Why aren't there wheels for Windows for 1.0.2?

**Comment by ArchieMeng** [comment]
> Why aren't there wheels for Windows for 1.0.2?

They are over there. You just need to click the show all button.
https://github.com/media2x/realcugan-ncnn-vulkan-python/releases/download/1.0.2/realcugan-ncnn-vulkan-python-1.0.2-windows_3.10.zip

**Comment by God-damnit-all** [comment]
Wow do I feel stupid.
